### ISSUE TITLE
[Question] Place label on centroid in static plot

### ISSUE THREAD

**Issue by cakiki** [TutteInstitute/datamapplot#9]
I really like the way labels are placed on the clusters themselves in dynamic plots. Is there a way to do that for static plots?

**Comment by cakiki** [comment]
This might also help make the map less cluttered when there's a large number of labels

**Comment by lmcinnes** [comment]
I actually started with this approach, but struggled when there are a lot of labels -- if the text was large enough to read the plot got quite obscured. For the interactive plots I found this worked well because you can let the user zoom and reveal more labels as you go, so at any time there aren't that many labels on screen.

I can have a look at whether it might be tractable to add this as an option to the static plots since it can work when you don't have many labels, but I admit to not being keen on that approach in general.

**Comment by MNoichl** [comment]
Quick heads up: I noticed a problem with pylabeladjust mishandling texts that were not left & bottom aligned. Didn't matter for the other use-cases, but here it was a problem. It should be fixed now.

**Comment by MNoichl** [comment]
Digging into your code, @lmcinnes, turns out it wasn't a problem, because you were using the rectangles_adjusted[["x_center", "y_center"]] values. I had removed them in the update because they seemed superfluous. I have re-added them now, so from version 0.1.13 things should work again.

**Comment by lmcinnes** [comment]
It pairs very well with (and updated version of) ``dynamic_label_size=True``, so be sure to try out that setting as well. Thanks for taking the time to look at it.
